### ISSUE TITLE
starting

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/angulillos-neo4j#1]
@pablopareja here we go :+1:

**Comment by eparejatobes** [comment]
The idea is to follow the same pattern as in [bio4j/angulillos-titan](https://github.com/bio4j/angulillos-titan); I think that the only non-obvious things will be related with indices, due to their messy state in Neo4j. This should be based on **Neo4j 2.1**. See
- [TitanUntypedGraph](https://github.com/bio4j/angulillos-titan/blob/master/src/main/java/com/bio4j/angulillos/titan/TitanUntypedGraph.java)
- [TitanTypedVertexIndex](https://github.com/bio4j/angulillos-titan/blob/master/src/main/java/com/bio4j/angulillos/titan/TitanTypedVertexIndex.java)
- [TitanTypedEdgeIndex](https://github.com/bio4j/angulillos-titan/blob/master/src/main/java/com/bio4j/angulillos/titan/TitanTypedEdgeIndex.java)

**Comment by pablopareja** [comment]
yeahhh! :goat:

**Comment by eparejatobes** [comment]
this could help too: https://github.com/bio4j/angulillos/tree/impl/neo4j
